### ISSUE TITLE
容器和kubernetes学习困惑

### ISSUE THREAD

**Issue by pytimer** [rootsongjc/qa#1]
# Question

  - [Kubernetes](https://kubernetes.io)
  - Others

## Content

你好，我最近在接触容器和kubernetes相关方面，也有看你的博客来自己搭建kubernetes环境学习，对这方面比较感兴趣，想要请教下，该如何去学习这方面的知识，感觉从网上看到的知识点都比较零散，想要比较系统的或者逐步的有计划的学习，希望可以解答下，谢谢。:-)

**Comment by rootsongjc** [comment]
@pytimer 我想你应该也是从我的Kubernetes&Cloud Native社区过来的吧。学习开源技术最重要的还是要有应用场景，而且还有看你学习的初衷是什么？你可以边学习边分享，在分享中进步。

**Comment by huweihuang** [comment]
如果想系统地学习k8s，看官方文档最实用，地址见[官方文档](https://kubernetes.io/docs/concepts/)，中文的文档，推荐一个地址[k8smeetup](https://k8smeetup.github.io/docs/concepts/)。如果水平足够当然是阅读[k8s源码](https://github.com/kubernetes/kubernetes)，毕竟源码是第一手资料，官方文档是第二手资料，其他文档和博客是第三手资料。

**Comment by llitfkitfk** [comment]
1. [docker官方文档](https://docs.docker.com/)
2. [k8s官方文档](https://kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational)
3. [docker群组与相关书籍](https://t.me/dockertutorial)
4. [docker/容器/kubernets相关书籍](https://t.me/bookmark)

**Comment by rootsongjc** [comment]
另外你也可以给Kubernetes汉化提交贡献，也能帮你解释一帮志同道合的人，也能学习kubernetes，详见https://github.com/kubernetes/kubernetes-docs-zh

**Comment by l453595892** [comment]
其实在我看来学习kubernetes主要是想象应用场景。而且这个东西现在最好是能找一个真实的需求。比如日志集群监控集群。或者k8s自身的优化。都是可以学习的。

**Comment by pytimer** [comment]
谢谢各位的回复和网站书籍。现在是没有实际场景，基本上是自己想要学习，所以搭建了两个节点的环境在试验。

**Comment by guleng** [comment]
@pytimer  我滴朋友   推荐你https://jimmysong.io/kubernetes-handbook/   我是看这个慢慢接触了解的
希望能帮到你。

**Comment by guleng** [comment]
@pytimer  我滴朋友   推荐你https://jimmysong.io/kubernetes-handbook/   我是看这个慢慢接触了解的
希望能帮到你。

**Comment by guleng** [comment]
@pytimer  我滴朋友   推荐你https://jimmysong.io/kubernetes-handbook/   我是看这个慢慢接触了解的
希望能帮到你。

**Comment by iiitux** [comment]
https://github.com/hackstoic/kubernetes_practice/blob/master/%E5%8F%82%E8%80%83%E8%B5%84%E6%96%99.md?from=groupmessage&isappinstalled=0

有人总结了k8s相应的文档。可以参考下
