### ISSUE TITLE
如何系统高效阅读k8s源码

### ISSUE THREAD

**Issue by huweihuang** [rootsongjc/qa#2]
# Question
  - [Kubernetes](https://kubernetes.io)

## Content

1. 怎么系统高效地阅读k8s的源码，毕竟源码太多，希望可以从以下pod的创建流程的方式阅读。
![image](https://user-images.githubusercontent.com/29064882/42730903-b1a23c64-8834-11e8-8fde-b6f862bc5f75.png)
2. 希望推荐高质量的k8s源码分析的文章。

**Comment by Tutotu** [comment]
k8s 代码封装太厉害，想我这边的小白读起来，真是很费力呀

**Comment by rootsongjc** [comment]
顺藤摸瓜，不可能一口吃一个胖子，从你要解决的问题入手。

**Comment by daimazai** [comment]
如果就想读呢

**Comment by rootsongjc** [comment]
@daimazai 那就读吧😄
