### ISSUE TITLE
Registry s3 storage

### ISSUE THREAD

**Issue by AmourLinux** [rootsongjc/qa#4]
# Question

- Others
- Technologies
  - Docker

## Content

我配置了一个私有registry，后端存储是aws的s3。我上传一个image后，多久会同步到s3？

**Comment by rootsongjc** [comment]
@AmourLinux 我没有用过S3存储，不过你的镜像仓库不是直接部署在S3上吗？为什么还说同步到S3上？从哪里同步？

**Comment by AmourLinux** [comment]
部署在本地，就是后端存储用的s3。
之前是用本地文件系统来着。

**Comment by rootsongjc** [comment]
那你使用的什么来镜像仓库管理工具？

**Comment by AmourLinux** [comment]
用的harbor-1.5版本，存储配置的s3
