### ISSUE TITLE
istio-gateway vs nginx-ingress

### ISSUE THREAD

**Issue by Runrioter** [rootsongjc/qa#5]
# Question

- Technologies
  - [Istio](https://istio.io)
  - [Kubernetes](https://kubernetes.io)

## Content

istio-gateway和nginx-ingress定位是不是重合了，如果我用istio，是不是就可以不用nginx-ingress等Ingress Resourcel了

谢谢回答

**Comment by rootsongjc** [comment]
是这样的，Istio同时使用了Envoy做数据平面的proxy也作为了Gateway，从Istio 0.8起已经不再使用Kubernetes的Ingress，参考：http://www.servicemesher.com/blog/introducing-the-istio-v1alpha3-routing-api/

**Comment by Runrioter** [comment]
@rootsongjc  多谢宋老师
